spring:
  application:
    name: webServiseApp
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 9091
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:4433/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
